services:
  mysql:
    image: mysql:8.0
    container_name: buildweb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodorderonline
      MYSQL_USER: buildweb
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-network

volumes:
  mysql-data:

networks:
  spring-network:
    driver: bridge